/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./Pages/**/*.{razor,cshtml}",
    "./Shared/**/*.razor",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#7e7576",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed": "#1b1b1b",
        "background": "#fcf9f8",
        "on-tertiary-container": "#069669",
        "surface": "#fcf9f8",
        "error-container": "#ffdad6",
        "surface-container": "#f0edec",
        "on-error-container": "#93000a",
        "on-background": "#1c1b1b",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed-variant": "#003fa4",
        "surface-container-low": "#f6f3f2",
        "on-tertiary-fixed": "#002114",
        "primary-fixed-dim": "#c6c6c6",
        "on-tertiary": "#ffffff",
        "secondary-container": "#366de9",
        "inverse-primary": "#c6c6c6",
        "secondary-fixed": "#dae1ff",
        "tertiary-container": "#002114",
        "surface-variant": "#e5e2e1",
        "surface-dim": "#dcd9d9",
        "tertiary-fixed-dim": "#68dba9",
        "surface-container-highest": "#e5e2e1",
        "on-primary-container": "#848484",
        "primary-container": "#1b1b1b",
        "surface-container-high": "#ebe7e7",
        "surface-tint": "#5e5e5e",
        "on-error": "#ffffff",
        "inverse-surface": "#313030",
        "tertiary-fixed": "#85f8c4",
        "on-surface-variant": "#4c4546",
        "primary": "#000000",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "secondary": "#0853ce",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        "outline-variant": "#cfc4c5",
        "primary-fixed": "#e2e2e2",
        "on-surface": "#1c1b1b",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#b3c5ff",
        "on-primary-fixed-variant": "#474747",
        "on-secondary-fixed": "#001849"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
