// Copyright (c) Heribert Gasparoli. SPDX-License-Identifier: AGPL-3.0-only

/// <summary>
/// Builds the sitemaps.org sitemap index that lists the per-locale sitemaps generated by the Docusaurus docs site.
/// </summary>
/// <param name="baseUrl">Absolute site base URL, e.g. https://klacks-software.ch; a trailing slash is ignored</param>

using System.Text;
using Klacks.Marketing.Localization;

namespace Klacks.Marketing.Seo;

public static class DocsSitemapIndexGenerator
{
    public const string IndexPath = "/docs-sitemap-index.xml";

    private const string DocsSitemapFileName = "sitemap.xml";
    private const string SitemapIndexNamespace = "http://www.sitemaps.org/schemas/sitemap/0.9";

    public static IReadOnlyList<string> BuildSitemapUrls(string baseUrl)
    {
        var trimmedBase = baseUrl.TrimEnd('/');

        return SupportedCultures.All
            .Select(culture => BuildSitemapUrl(trimmedBase, culture))
            .ToList();
    }

    public static string Build(string baseUrl)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        sb.AppendLine($"<sitemapindex xmlns=\"{SitemapIndexNamespace}\">");

        foreach (var url in BuildSitemapUrls(baseUrl))
        {
            sb.AppendLine("  <sitemap>");
            sb.AppendLine($"    <loc>{url}</loc>");
            sb.AppendLine("  </sitemap>");
        }

        sb.AppendLine("</sitemapindex>");
        return sb.ToString();
    }

    // Docusaurus writes the default locale's sitemap to the docs root and every other locale's
    // into its own locale folder; the folder name is the culture's DocsLocale (zh-CN -> zh-Hans).
    private static string BuildSitemapUrl(string trimmedBase, SupportedCulture culture)
    {
        var docsRoot = $"{trimmedBase}{ExternalLinks.DocsBasePath}";

        return culture.Code == SupportedCultures.DefaultCode
            ? $"{docsRoot}{DocsSitemapFileName}"
            : $"{docsRoot}{culture.DocsLocale}/{DocsSitemapFileName}";
    }
}
